"""Emit paper/numbers.tex from the committed results JSON.

Every number that appears in manuscript.tex is a \\newcommand read from the
same JSON files that produced the figures, so the paper can never drift from
the committed experimental artifacts.  Missing files yield "TBD" placeholders
so the draft compiles before results land.

Run: python make_paper_numbers.py
"""
from __future__ import annotations

import json
from pathlib import Path

from src.backdoors import config

OUT = Path("paper") / "numbers.tex"
RESULTS = config.RESULTS_DIR


def load(name: str) -> dict | None:
    p = RESULTS / name
    return json.loads(p.read_text()) if p.exists() else None


def num(v, nd=3) -> str:
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "TBD"


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


lines = ["% Auto-generated by make_paper_numbers.py -- do not edit by hand.",
         "% Every number below is read from the committed results/*.json files.",
         ""]

poison = load("poison_0.05_1.json")
if poison and "metrics" in poison:
    m = poison["metrics"]
    lines += [
        macro("nRuns", 1),
        macro("nPilotRate", "0.05"),
        macro("asr", num(m.get("asr", 0.0))),
        macro("benign", num(m.get("benign_acc", 0.0))),
        macro("stealth", num(m.get("stealth_acc", 0.0))),
        macro("leak", num(m.get("target_leak", 0.0))),
        macro("nPoisonSteps", poison.get("steps", "TBD")),
        macro("nTrainSize", 3000),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("nRuns", "nPilotRate", "asr", "benign", "stealth", "leak",
               "nPoisonSteps", "nTrainSize")]

clean = load("poison_0.0_1.json")
if clean and "metrics" in clean:
    cm = clean["metrics"]
    lines += [
        macro("cleanAsr", num(cm.get("asr", 0.0))),
        macro("cleanBenign", num(cm.get("benign_acc", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in ("cleanAsr", "cleanBenign")]

persist = load("persist_p0.05_s1.json")
if persist and persist.get("partial"):
    persist = None  # crashed mid-run; wait for the completed file
if persist and persist.get("checkpoints"):
    cps = sorted(persist["checkpoints"], key=lambda c: c["step"])
    final = cps[-1]
    lines += [
        macro("persistSteps", persist.get("persist_steps", "TBD")),
        macro("asrAfterPersist", num(final.get("asr", 0.0))),
        macro("benignAfterPersist", num(final.get("benign_acc", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("persistSteps", "asrAfterPersist", "benignAfterPersist")]

unl = load("unlearn_ascent_p0.05_s1.json")
if unl and unl.get("partial"):
    unl = None  # crashed mid-run; wait for the completed file
if unl and unl.get("checkpoints"):
    cps = sorted(unl["checkpoints"], key=lambda c: c["step"])
    final = cps[-1]
    lines += [
        macro("unlearnSteps", unl.get("unlearn_steps", "TBD")),
        macro("asrAfterUnlearn", num(final.get("asr", 0.0))),
        macro("benignAfterUnlearn", num(final.get("benign_acc", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("unlearnSteps", "asrAfterUnlearn", "benignAfterUnlearn")]

det = load("detect_p0.05_s1.json")
if det:
    pr = det.get("probe", {})
    ab = det.get("ablation", {})
    lines += [
        macro("concatAuc", num(pr.get("concat_auc", 0.0))),
        macro("ablationAcc", num(ab.get("accuracy", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in ("concatAuc", "ablationAcc")]

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(lines)} lines)")
