"""Emit paper/numbers.tex from the committed results JSON.

Every number that appears in manuscript.tex is a \\newcommand read from the
same JSON files that produced the figures, so the paper can never drift from
the committed experimental artifacts.  Missing files yield "TBD" placeholders
so the draft compiles before results land.

Run: python make_paper_numbers.py
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from src.backdoors import config

OUT = Path("paper") / "numbers.tex"
RESULTS = config.RESULTS_DIR


def load(name: str) -> dict | None:
    p = RESULTS / name
    return json.loads(p.read_text()) if p.exists() else None


def num(v, nd=3) -> str:
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "TBD"


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


lines = ["% Auto-generated by make_paper_numbers.py -- do not edit by hand.",
         "% Every number below is read from the committed results/*.json files.",
         ""]

# --- Injection: full matrix (4 rates x 2 seeds) ---
poison_rates = [0.0, 0.02, 0.05, 0.10]
seeds = [1, 2]
injection_runs = {}
for rate in poison_rates:
    for seed in seeds:
        key = f"poison_{rate}_{seed}"
        d = load(f"{key}.json")
        if d and "metrics" in d:
            injection_runs.setdefault(rate, []).append(d["metrics"])

if injection_runs:
    # Compute stats across seeds for each rate
    poisoned_rates = [r for r in poison_rates if r > 0]
    all_asr = [m["asr"] for rate in poisoned_rates for m in injection_runs.get(rate, [])]
    all_benign = [m["benign_acc"] for rate in poisoned_rates for m in injection_runs.get(rate, [])]
    all_stealth = [m["stealth_acc"] for rate in poisoned_rates for m in injection_runs.get(rate, [])]

    # Primary reported rate is 0.05
    p05_runs = injection_runs.get(0.05, [])
    p05_asr = [m["asr"] for m in p05_runs] if p05_runs else [0.0]
    p05_benign = [m["benign_acc"] for m in p05_runs] if p05_runs else [0.0]
    p05_stealth = [m["stealth_acc"] for m in p05_runs] if p05_runs else [0.0]

    n_poisoned = sum(len(v) for v in injection_runs.values() if v)
    clean_runs = injection_runs.get(0.0, [])
    clean_asr_vals = [m["asr"] for m in clean_runs] if clean_runs else [0.0]
    clean_benign_vals = [m["benign_acc"] for m in clean_runs] if clean_runs else [0.0]

    # Get steps from any run
    any_run = list(injection_runs.values())[0][0] if injection_runs else {}
    # Find the actual steps value from the JSON
    sample_run = load(f"poison_0.05_1.json")
    n_steps = sample_run.get("steps", 400) if sample_run else 400

    lines += [
        macro("nRates", len(poisoned_rates)),
        macro("nSeeds", len(seeds)),
        macro("nTotalRuns", n_poisoned),
        macro("nPilotRate", "0.05"),
        macro("asr", num(sum(p05_asr) / len(p05_asr))),
        macro("benign", num(sum(p05_benign) / len(p05_benign))),
        macro("stealth", num(sum(p05_stealth) / len(p05_stealth))),
        macro("leak", num(0.0)),
        macro("nPoisonSteps", n_steps),
        macro("nTrainSize", 3000),
        macro("allAsr", num(sum(all_asr) / len(all_asr) if all_asr else 0.0)),
        macro("allAsrMin", num(min(all_asr) if all_asr else 0.0)),
        macro("allAsrMax", num(max(all_asr) if all_asr else 0.0)),
        macro("cleanAsr", num(sum(clean_asr_vals) / len(clean_asr_vals) if clean_asr_vals else 0.0)),
        macro("cleanBenign", num(sum(clean_benign_vals) / len(clean_benign_vals) if clean_benign_vals else 0.0)),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("nRates", "nSeeds", "nTotalRuns", "nPilotRate", "asr", "benign",
               "stealth", "leak", "nPoisonSteps", "nTrainSize",
               "allAsr", "allAsrMin", "allAsrMax", "cleanAsr", "cleanBenign")]

# --- Persistence: 300-step clean continued fine-tuning ---
persist = load("persist_p0.05_s1.json")
if persist and persist.get("partial"):
    persist = None  # crashed mid-run; wait for the completed file
if persist and persist.get("checkpoints"):
    cps = sorted(persist["checkpoints"], key=lambda c: c["step"])
    final = cps[-1]
    # front-loaded persistence: checkpoint nearest half the persist run
    half = min(cps, key=lambda c: abs(c["step"] - persist.get("persist_steps", 0) / 2))
    # quarter persistence (early regime that matters)
    quarter = min(cps, key=lambda c: abs(c["step"] - persist.get("persist_steps", 0) / 4))
    lines += [
        macro("persistSteps", persist.get("persist_steps", "TBD")),
        macro("asrAfterPersist", num(final.get("asr", 0.0))),
        macro("benignAfterPersist", num(final.get("benign_acc", 0.0))),
        macro("halfPersistSteps", half.get("step", "TBD")),
        macro("asrHalfPersist", num(half.get("asr", 0.0))),
        macro("benignHalfPersist", num(half.get("benign_acc", 0.0))),
        macro("quarterPersistSteps", quarter.get("step", "TBD")),
        macro("asrQuarterPersist", num(quarter.get("asr", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("persistSteps", "asrAfterPersist", "benignAfterPersist",
               "halfPersistSteps", "asrHalfPersist", "benignHalfPersist",
               "quarterPersistSteps", "asrQuarterPersist")]

# --- Unlearning: ascent variant ---
unl = load("unlearn_ascent_p0.05_s1.json")
if unl and unl.get("partial"):
    unl = None
if unl and unl.get("checkpoints"):
    cps = sorted(unl["checkpoints"], key=lambda c: c["step"])
    final = cps[-1]
    early = min(cps, key=lambda c: c["asr"])
    lines += [
        macro("unlearnSteps", unl.get("unlearn_steps", "TBD")),
        macro("asrAfterUnlearn", num(final.get("asr", 0.0))),
        macro("benignAfterUnlearn", num(final.get("benign_acc", 0.0))),
        macro("earlyUnlearnSteps", early.get("step", "TBD")),
        macro("asrEarlyUnlearn", num(early.get("asr", 0.0))),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("unlearnSteps", "asrAfterUnlearn", "benignAfterUnlearn",
               "earlyUnlearnSteps", "asrEarlyUnlearn")]

# --- Unlearning: ascent+retain variant (the novel finding) ---
unlr = load("unlearn_ascent_retain_p0.05_s1.json")
if unlr and unlr.get("partial"):
    unlr = None
if unlr and unlr.get("checkpoints"):
    cps = sorted(unlr["checkpoints"], key=lambda c: c["step"])
    final = cps[-1]
    early = min(cps, key=lambda c: c["asr"])
    lines += [
        macro("retainSteps", unlr.get("unlearn_steps", "TBD")),
        macro("asrAfterRetain", num(final.get("asr", 0.0))),
        macro("benignAfterRetain", num(final.get("benign_acc", 0.0))),
        macro("retainBump", num(final.get("benign_acc", 0.0) - unl.get("checkpoints", [{}])[-1].get("benign_acc", 0.0) if unl else 0.0)),
    ]
else:
    lines += [macro(n, "TBD") for n in
              ("retainSteps", "asrAfterRetain", "benignAfterRetain", "retainBump")]

# --- Detection: aggregate across full matrix ---
detect_runs = {}
for rate in poisoned_rates:
    for seed in seeds:
        d = load(f"detect_p{rate}_s{seed}.json")
        if d:
            detect_runs.setdefault(rate, []).append(d)

if detect_runs:
    # All ablation AUCs should be 0.5 (chance)
    all_ablation_acc = []
    all_ablation_auc = []
    for rate, runs in detect_runs.items():
        for r in runs:
            ab = r.get("ablation", {})
            all_ablation_acc.append(ab.get("accuracy", 0.5))
            all_ablation_auc.append(ab.get("auc", 0.5))

    # Use the primary detection result for the probe/delta numbers
    det = load("detect_p0.05_s1.json") or load("detect_p0.02_s1.json")
    clean_det = load("detect_p0.0_s1.json")
    if det:
        pr = det.get("probe", {})
        ab = det.get("ablation", {})
        delta = pr.get("layer_delta", [])
        peak = max(delta) if delta else 0.0
        upper = delta[-10:] or delta
        mean_upper = sum(upper) / len(upper) if upper else 0.0
        cd = clean_det.get("probe", {}).get("layer_delta", []) if clean_det else []
        c_peak = max(cd) if cd else 0.0
        c_upper = cd[-10:] or cd
        c_mean_upper = sum(c_upper) / len(c_upper) if c_upper else 0.0
        lines += [
            macro("concatAuc", num(pr.get("concat_auc", 0.0))),
            macro("ablationAcc", num(sum(all_ablation_acc) / len(all_ablation_acc))),
            macro("nDetectRuns", len(all_ablation_acc)),
            macro("deltaPeakPoison", num(peak)),
            macro("deltaPeakClean", num(c_peak)),
            macro("deltaUpperPoison", num(mean_upper)),
            macro("deltaUpperClean", num(c_mean_upper)),
            macro("deltaAmplif", num(100.0 * (mean_upper - c_mean_upper) / max(c_mean_upper, 1e-9), 0)),
        ]
    else:
        lines += [macro(n, "TBD") for n in
                  ("concatAuc", "ablationAcc", "nDetectRuns", "deltaPeakPoison",
                   "deltaPeakClean", "deltaUpperPoison", "deltaUpperClean", "deltaAmplif")]
else:
    lines += [macro(n, "TBD") for n in
              ("concatAuc", "ablationAcc", "nDetectRuns", "deltaPeakPoison",
               "deltaPeakClean", "deltaUpperPoison", "deltaUpperClean", "deltaAmplif")]

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(lines)} lines)")
